DROP DATABASE IF EXISTS newdb;

DROP ROLE IF EXISTS newdb; 

CREATE ROLE newdb LOGIN
  ENCRYPTED PASSWORD 'md568cefad35fed037c318b1e44cc3480cf' -- password: pass
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE;

CREATE DATABASE newdb WITH OWNER = newdb;